Digg 167 beta
diggsweden/dataportal-web pull request #170
Opened 2024-01-18 07:55 UTC by AlessandroGasperini

2024-01-18 16:59 UTC, Kopin1 requested changes

2024-01-18 16:59 UTC, Kopin1 commented on components/content/ListPage/index.tsx
> +  const router: NextRouter | any = useRouter();
kan vi få bort any?

2024-01-18 20:24 UTC, AlessandroGasperini commented on components/content/ListPage/index.tsx
> +  const router: NextRouter | any = useRouter();
Fixat

2024-01-19 08:09 UTC, Kopin1 approved these changes

2024-01-19 08:25 UTC, merged