DIGG-463: Improving search implementation and caching organisation names
diggsweden/dataportal-web pull request #502
Opened 2024-11-14 13:16 UTC by MikaMunterud

# Pull Request Description

Please include a summary of the change and which issue is fixed or added.
Please also include relevant motivation and context.
List any dependencies that are required for this change.

Fixes #(issue)

## Checklist

- [x] Changes are limited to a single goal (avoid scope creep)
- [x] I confirm that I have read any Contribution and Development guidelines (CONTRIBUTING and DEVELOPMENT) and are following their suggestions.
- [x] I confirm that I wrote and/or have the right to submit the contents of my Pull Request, by agreeing to the _Developer Certificate of Origin_, (adding a 'sign-off' to my commits).

2024-11-14 21:25 UTC, Kopin1 commented on components/content/Search/SearchFilters/index.tsx
> +                        }
kan det vara läge ett lägga att ha funktion som vi kan återanvända istället för att skriva nästan samma kod varje gång?

2024-11-14 21:25 UTC, Kopin1 commented on utilities/entrystoreUtil.ts
> +  facetSpec: any,
Vi kanske kan göra något åt alla dessa any types på sikt, inte i denna PR

2024-11-15 07:43 UTC, Kopin1 requested changes

2024-11-15 07:43 UTC, Kopin1 commented on types/entrystore-js.d.ts
> +  export class EntryStoreUtil {
Behöver dessa vara en class? Annars är det bättre att göra dom till types eller interfaces, vad vi nu föredrar. Ser ut som att vi använder dom som types i koden.

2024-11-15 07:43 UTC, Kopin1 commented on types/entrystore-js.d.ts
> +  export class EntryStore {
Samma här

2024-11-15 07:43 UTC, Kopin1 commented on types/entrystore-js.d.ts
> +  export class SolrQuery {
Samma här

2024-11-15 07:52 UTC, MikaMunterud commented on types/entrystore-js.d.ts
> +  export class EntryStoreUtil {
Enligt Entrystore's documentation så är de classer med inbyggda funktioner, ändrar jag det till types får jag fel i koden där det används.
<img width="659" alt="image" src="https://github.com/user-attachments/assets/ccf2c9be-40df-407f-b5fa-4b8f76ccd600">
<img width="873" alt="image" src="https://github.com/user-attachments/assets/295e66f0-a9a7-4a43-8fe7-78f1623bab85">

2024-11-15 07:52 UTC, MikaMunterud commented on types/entrystore-js.d.ts
> +  export class EntryStore {
Samma som ovan kommentar

2024-11-15 07:52 UTC, MikaMunterud commented on types/entrystore-js.d.ts
> +  export class SolrQuery {
Samma som ovan kommentar

2024-11-15 07:56 UTC, Kopin1 commented on types/entrystore-js.d.ts
> +  export class EntryStoreUtil {
Ok! Ja då ska det vara en Class, den koden syns inte i PR av någon anledning.

2024-11-15 07:56 UTC, Kopin1 approved these changes
👍

2024-11-15 08:02 UTC, merged