Digg 472: Follow specification facet
diggsweden/dataportal-web pull request #527
Opened 2024-12-05 14:41 UTC by AlessandroGasperini

New filter for datasets.
[https://dgroupse.atlassian.net/browse/DIGG-472](url)

2024-12-05 16:12 UTC, MikaMunterud requested changes
Lite kommentarer för att förenkla koden 😊

2024-12-05 16:12 UTC, MikaMunterud commented on features/search/search-filters/index.tsx
> +                    } else if (key === spec) {
Om du har tid att kika på det skulle det kanske vara bra att se om det går att göra en else enbart som gäller för alla checkboxar? Det kommer komma flera flera checkboxar i framtiden och skulle vara skönt om vi kan slippa göra en elseif för varje 😊

2024-12-05 16:12 UTC, MikaMunterud commented on locales/sv/resources.json
> +  "http://purl.org/dc/terms/conformsTo": "Följer specifikation",
Liten skitsak men skulle vara nice om vi kan fortsätta med att translation filerna i bokstavsordning 😉

2024-12-05 16:12 UTC, MikaMunterud commented on yarn.lock
Är det något som har missats tidigare? Lite oklart varför lockfilen behöver uppdateras om inget nytt npm paket har lagts till?

2024-12-05 16:55 UTC, AlessandroGasperini commented on yarn.lock
Ser ut som det, har nya dev och får ny lock fil

2024-12-05 16:56 UTC, AlessandroGasperini commented on features/search/search-filters/index.tsx
> +                    } else if (key === spec) {
Bröt ut hur vi sätter värden i SearchCheckboxFilter

2024-12-06 08:08 UTC, Kopin1 requested changes

2024-12-06 08:08 UTC, Kopin1 commented on components/typography/heading/index.tsx
> +      {/* @ts-expect-error - React children type mismatch with custom heading element */}
Samma här

2024-12-06 08:08 UTC, Kopin1 commented on components/typography/body-variant/index.tsx
> +    // @ts-expect-error - React children type mismatch with custom body element
varför behövs denna?

2024-12-06 08:12 UTC, AlessandroGasperini commented on components/typography/body-variant/index.tsx
> +    // @ts-expect-error - React children type mismatch with custom body element
borta

2024-12-06 08:12 UTC, AlessandroGasperini commented on yarn.lock
borta

2024-12-09 11:42 UTC, MikaMunterud approved these changes
LGTM 😊

2024-12-09 12:27 UTC, merged