DIGG-483: Uppdating url structure for concepts, terminologies and specifications
diggsweden/dataportal-web pull request #530
Opened 2024-12-06 17:05 UTC by MikaMunterud

# Pull Request Description

Handling entries in two different ways depending on if it is an so called external specification or internal specification makes the code more difficult to handle when different cases needs to fetched from entrystore in different ways. 

It is better to handle them in the same way as datasets and organisations where the context id and entry id is used to fetch the entry from entrystore. 

This code includes handling of permanent redirecting the old url structures to the new format. This has been tested to be inputted in a middleware but it seems like the middleware has restrictions regarding imported functions, for example EntryStore or outside functions that uses EntryStore. For that reason is the redirection handled in each path that has been previously used.

## Checklist

- [x] Changes are limited to a single goal (avoid scope creep)
- [x] I confirm that I have read any Contribution and Development guidelines (CONTRIBUTING and DEVELOPMENT) and are following their suggestions.
- [x] I confirm that I wrote and/or have the right to submit the contents of my Pull Request, by agreeing to the _Developer Certificate of Origin_, (adding a 'sign-off' to my commits).

2024-12-07 12:05 UTC, Kopin1 requested changes

2024-12-07 12:05 UTC, Kopin1 commented on pages/concepts/[concept]/index.tsx
> +  try {
Vi gör en ganska liknande request här verkar det som. kan vi göra en function som vi använder på alla sidor?

2024-12-07 14:47 UTC, MikaMunterud commented on pages/concepts/[concept]/index.tsx
> +  try {
FIxat

2024-12-09 11:08 UTC, Kopin1 approved these changes
👍

2024-12-09 11:23 UTC, merged